### ISSUE TITLE
create edit command

### ISSUE THREAD

**Issue by wannyu** [wannyu/orbital-dreadfulDragon#14]
allow users to edit food in their list

**Comment by sherylau** [comment]
if edit servings to 0 - delete

**Comment by sherylau** [comment]
still need to check for user input - whether it is in the correct order, whether it is a valid date etc.

**Comment by sherylau** [comment]
also need to check if user input is in database - if it is not prompt for a valid response

**Comment by wannyu** [comment]
new problem: the custom keyboard (displaying the buttons) will forever be present at the bottom right hand side. theres no way to destroy the button after 1 time usage

**Comment by wannyu** [comment]
nvm its not possible (unless we dont use buttons) since its made to be like that in the telegram bot documentation
