### ISSUE TITLE
make add and consume function take in many inputs at the same time

### ISSUE THREAD

**Issue by wannyu** [wannyu/orbital-dreadfulDragon#5]
since users can only add or consume 1 food type when they type /add or /consume, it would be more convenient for them if the bot can take in many inputs at the same time 

(/addmany and /consumemany in README)

**Comment by sherylau** [comment]
if there is only 1 food entered - prompt user to use /add or just add it to food list?

**Comment by sherylau** [comment]
^ same for consumemany

**Comment by wannyu** [comment]
/addmany and /consumemany functions work if user only enter 1 row right? then we can juz leave it?
