### ISSUE TITLE
look for new server

### ISSUE THREAD

**Issue by sherylau** [wannyu/orbital-dreadfulDragon#6]
current server - google colab, need find one that allow users to directly interact with our bot

**Comment by wannyu** [comment]
pythonanywhere? but it crashes once in a few days

**Comment by wannyu** [comment]
currently using python anywhere for milestone 2 submission. will change to a more reliable server by milestone 3

**Comment by wannyu** [comment]
Heroku + postgresql (offered within Heroku) works pretty well
